version: '2'

services:
    symfony_mysql:
        container_name: symfony_mysql
        image: mysql:5.7
        ports:
            - 5000:3306
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always
    symfony_test:
        container_name: symfony_test 
        image: denzdacs/symfony-env 
        ports:
            - 8000:80
        volumes:
            - .:/var/www/site
        working_dir: /var/www/site
        depends_on:
            - symfony_mysql 
        restart: always
volumes:
    db-data:
