# config/routes.yaml
home:
    path: /
    controller: App\Controller\Home::index
about:
    path: /about
    controller: App\Controller\About:index
logout:
    path: /logout
    controller: App\Controller\Auth::logout
404:
    path: /{wildcard}
    controller: App\Controller\PageNotFound::index
